idf_component_register(
    SRCS
        "app_main.c"
        "wifi_manager.c"
        "console_cli.c"
        "button_manager.c"
        "trainer_manager.c"
        "web_server.c"
    INCLUDE_DIRS "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        driver
        mdns
        bt
)
